### ISSUE TITLE
Use zoom in expressions as a variable

### ISSUE THREAD

**Issue by sztanko** [mapbox/carto#269]
Would love to have to use zoom an other variables in expressions.

Something like this:

``` css
marker-width: zoom/2;
```

Currently it just gives the following error:
"Object zoom has no method 'operate'"

**Comment by nebulon42** [comment]
Think this is done, so closing. Re-open if I'm mistaken.

**Comment by eschwartz** [comment]
Is the `@zoom` variable implemented? I don't see it documented anywhere, and I haven't been able to get it to work.

**Comment by pnorman** [comment]
> Is the @zoom variable implemented? I don't see it documented anywhere, and I haven't been able to get it to work.

Same issues.

**Comment by nebulon42** [comment]
I'll check. The relevant bit though is: https://gist.github.com/springmeyer/7226517#gistcomment-1307394

**Comment by nebulon42** [comment]
This works. But you have to pass the variables and their values to Mapnik. To get this to work in Kosmtik I had to change https://github.com/kosmtik/kosmtik/blob/master/src/back/Tile.js#L34 to
````
map.render(im, {scale: project.mml.scale, variables: {zoom: this.z}}, cb);
````

Not sure how feasible that is in other contexts. This would need more documentation on the Mapnik side. For carto it would be sufficient to state that you can pass variables of the form `@var` within strings to Mapnik >= 3.0.0.

**Comment by pnorman** [comment]
Does the carto binary do this? I can't find it in https://github.com/mapbox/carto/blob/c40214a34833641690541b14d4a41eb6fc5184d0/bin/carto#L13

**Comment by nebulon42** [comment]
I have edited my comment above, because what I meant to write is that you have to pass the variables to Mapnik _at runtime_. This is nothing that carto can do.

**Comment by csytsma** [comment]
If anyone is wondering about this being supported in TileMill, I just checked and it does work.  The syntax you want to use is:
`
text-name: '@zoom' 
`

The apostrophes will pass it as text through Carto.js, then Mapnik will pick up the variable. At least, that's how I interpreted https://gist.github.com/springmeyer/7226517#gistcomment-1307394

It is somewhat limited, in that you have to pass any operations within the quotes, and can't be within a filter.

For example, in my roads.mss, I had to put it at the top, before any #road_high{} type filters.  Any operations need to be done directly on the @zoom variable, you can't do it on a variable you assigned it to.

So this works:
`@roads_path: '@zoom * @zoom *  .005';
line-width: @roads_path;`
or
`line-width: '@zoom * @zoom *  .005';`

This doesn't:
`line-width: @roads_path / 2;`
