### ISSUE TITLE
Add mml documentation

### ISSUE THREAD

**Issue by pnorman** [mapbox/carto#274]
The referenced docs at http://mapbox.com/carto/ do not contain any specifications for .mml files, which carto parses. Docs should be added for these files.

**Comment by alexandervlpl** [comment]
There is no longer an MML section in the README, and it would be great to have one somewhere in the docs.

I think people are using CartoCSS in their own rendering workflows, which means `project.mml` is not always an "internal" TileMill / Mapbox Studio config file for them. It's a file that's created and edited manually, and there can be a lot of guesswork involved.

**Comment by matkoniecz** [comment]
> There is no longer an MML section in the README, and it would be great to have one somewhere in the docs.

And from what I see it was just example of beginning of mml file (see https://github.com/mapbox/carto/commit/02a657f3731c0409aaf5c98d33175dd950399cf2).

**Comment by nebulon42** [comment]
Starting on documentation. Notes to self:
* interactivity - Tilemill only feature?

**Comment by nebulon42** [comment]
I have started on a MML documentation. But I need some help. Could you please read over it and point out what is missing or wrong. Please try also to answer the points I found in https://github.com/mapbox/carto/issues/274#issuecomment-304537835.

It would be also nice to know what MML and MSS actually mean. Mapnik Map Layers? Mapnik Style Sheet? Does anybody know? :)

@pnorman @springmeyer @gravitystorm @math1985 @artemp

**Comment by pnorman** [comment]
> MML and MSS actually mean. Mapnik Map Layers? Mapnik Style Sheet?

MML and MSS both come from Cascadenik. I had always assumed mss stood for map style sheet, but can't find anything explicit.

**Comment by gravitystorm** [comment]
Maybe @migurski knows what mml and mss originally stood for? In my mind they were just acronyms (XML and CSS -> MML and MSS), so I don't know whether the M was for Mapnik or Map, or even if I'm barking up the wrong tree.

**Comment by gravitystorm** [comment]
> advanced (layer) - what can go in here?

I've used this before for layer attributes that are not defined in cartocss.  For example, the shapefile plugin takes an "encoding" attribute, so something like:

```
     "srs-name": "WGS84",
      "srs": "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs",
      "advanced": {
        "encoding": "windows-1252"
      },
```

```
   <Datasource>
       <Parameter name="file"><![CDATA[/tmp/foo.shp]]></Parameter>
       <Parameter name="type"><![CDATA[shape]]></Parameter>
       <Parameter name="encoding"><![CDATA[windows-1252]]></Parameter>
    </Datasource>
```

**Comment by nebulon42** [comment]
@gravitystorm thanks, that's interesting. When I look at the code for layers (https://github.com/mapbox/carto/blob/master/lib/carto/tree/layer.js#L8) then any parameter there should be serialized as parameter tag. So you should be able to specify the encoding of the shapefile directly beneath the datasource property.

**Comment by migurski** [comment]
I guess I never really defined them, but yeah: MML was Mapnik Markup Language and MSS was Mapnik Stylesheets, both adapted from HTML and CSS terminology. Before Mapbox forked the filename extension, [MML was XML](http://teczno.com/cascadenik/doc/). [Original blog post here](http://mike.teczno.com/notes/cascadenik.html).

**Comment by nebulon42** [comment]
Thanks @migurski. Why not define them now? :) What about Map Markup Language and Map Stylesheet? While carto targets Mapnik I think it might be good to keep possibilities open.

**Comment by nebulon42** [comment]
Thanks for the input, I'm closing this as resolved. If there are some features of the MML left undocumented or there are errors I welcome PRs.
