### ISSUE TITLE
Non-ordered nested zoomlevel selectors get ignored

### ISSUE THREAD

**Issue by math1985** [mapbox/carto#351]
Consider the following code.
```
#junctions {
  [highway = 'motorway_junction'][zoom >= 11],
  [junction = 'yes'][zoom >= 13] {
    [zoom >= 12] {
      name/text-fill: blue;
      name/text-name: "[name]";
      name/text-face-name: @oblique-fonts;
    }
    [zoom >= 15] {
      name/text-name: "[name]";
      name/text-face-name: @oblique-fonts;
    }
  }
}
```
This does not render junction=yes on z13 and z14, where I would expect it to be rendered. In addition, it renders junction=yes in black on z15 and larger. I would expect it to be rendered in blue.

See also #350.

**Comment by nebulon42** [comment]
I cannot reproduce this issue (anymore). @math1985 Could you please again verify if this still fails for you?

**Comment by math1985** [comment]
I cannot reproduce this either anymore, so I'll close this issue.
