### ISSUE TITLE
Numerical selector unexpectedly ignored

### ISSUE THREAD

**Issue by math1985** [mapbox/carto#370]
Consider the following Carto code:

    [way_pixels < 192000][way_pixels > 3000] { 
      line-width: 1;
    }

Carto translates this to the following filter:

    <Filter>([way_pixels] &gt; 3000)</Filter>

I would expect the following filter instead:

    <Filter>([way_pixels] &lt; 192000) and ([way_pixels] &gt; 3000)</Filter>

Reversing the quantifiers, or replacing < by <=, does give the expected output.

**Comment by springmeyer** [comment]
@math1985 - I think this is fixed in this pull: https://github.com/mapbox/carto/pull/393. Can you give it a try and let me know. /cc @gravitystorm @pnorman

**Comment by math1985** [comment]
Thanks! Not tested yet, but code looks good.

**Comment by math1985** [comment]
#369 is independent from this, right?

**Comment by math1985** [comment]
Do you have a way to find out which version of carto you are using?
