### ISSUE TITLE
text-wrap-width documentation is incorrect (characters vs pixels)

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/carto#376]
> Length of a chunk of text in characters before wrapping text

But it is not working this way. https://www.mapbox.com/tilemill/docs/guides/styling-labels/ turns out to have correct description

> You can wrap long labels onto multiple lines with the text-wrap-width property which specifies at what pixel width labels should start wrapping

**Comment by gravitystorm** [comment]
This text comes from [mapnik-reference](https://github.com/mapnik/mapnik-reference) and was fixed in https://github.com/mapnik/mapnik-reference/commit/051ec871a0096687a364a0501e6d1c124cd8696e

This issue can be closed.
