### ISSUE TITLE
Some carto errors are written to stdout not stderr

### ISSUE THREAD

**Issue by rnorris** [mapbox/carto#381]
In version v0.14.0 these errors are written to stdout:

. "carto: no input files ('carto -h or --help' for help)"
. "carto: please pass either a .mml file or .mss file"
. "carto: file does not exist: '" + input + "'"

Carto then immediately exits

I think the above errors should be using console.error() rather than console.log() so the messages are sent to stderr rather than stdout.

Interestingly git commit 19ac7b2fb072217a90edc081508a87d1c4111e40 attempts to fix this but I believe not quite fixing all cases properly.

**Comment by springmeyer** [comment]
fixed in edfb7ed
