### ISSUE TITLE
Error handling for missing brackets in CartoCSS syntax

### ISSUE THREAD

**Issue by knutole** [mapbox/carto#382]
Node/mapnik crashes on missing brackets in string, but it flies under the radar in carto.Renderer():

`building-height: "MAX_B_H]"; // missing bracket `

throws this error in node/mapnik:
`[Error: Failed to parse expression: "MAX_B_H]" in style 'layer' in BuildingSymbolizer of '/var/www/DATA/stylesheets/OOXYLDI.xml']`

Other syntax errors are nicely caught in `carto.Renderer()`, perhaps useful to catch this type syntax error also.

**Comment by springmeyer** [comment]
Not seeing any reason to keep this open. Not quoting will trigger the error. Quoting can allow values to be passed through unvalidated to Mapnik and can be useful too. Therefore I don't see value in trying to catch this error before Mapnik.
