### ISSUE TITLE
Flipped min/max zoom

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#385]
Just noticed https://github.com/mapbox/carto/commit/7deb1b86e060efee5ec358712683ec505542efa0#diff-d611a4d39a7dcd1c7e873eb1cec68bceR12, which looks odd. Clearly this is working correctly, but it looks mismatched. So I wonder if this is working because min/max are being interpreted incorrectly somewhere else in the stack.

**Comment by nebulon42** [comment]
Isn't this because zoom level and scale denominator are inverse proportional as [this table](https://wiki.openstreetmap.org/wiki/MinScaleDenominator) shows?

So if you want to set minzoom=9 you have to set maxscaledenominator=1100000 (example value).

**Comment by nebulon42** [comment]
I think this can be safely closed as per my comment above.
