### ISSUE TITLE
Ubuntu14.04 install - missing error cant find optimist

### ISSUE THREAD

**Issue by blu-elephant** [mapbox/carto#386]
I have used `carto` successfully about a month ago on a Ubuntu VM but having tried to use it yesterday (and having moved the VM) I'm getting error's from node to say that it cant find `optimist`. Why would this appear as an issue having not (knowingly) changed any configuration? I **can** find the optimist documentation (searching for `node-optimist`) and an `optimist.js` file on the system, so it was there. I had to fix other errors to enable node to find the `mapnik-reference` and `underscore` modules using `npm install /path/to/module`. I'm using carto offline so and apt-get won't work. Wondered if anyone can suggest the best way forward? Perhaps the best way to make sure I download `optimise` correctly to install with npm offline...or a way to use the `optimist.js` file a have via npm?

**Comment by springmeyer** [comment]
This sounds unrelated to carto. Sorry you are having trouble though. Sounds related to using apt to install node.js packages which I do not recommend. Instead use `npm` always.
