### ISSUE TITLE
raster-colorizer-stops not generating <RasterColorizer>

### ISSUE THREAD

**Issue by nathancahill** [mapbox/carto#390]
Carto:

```
raster-colorizer-stops: stop(0, #000) stop(255, #FFF);
```

Generated Mapnik XML:

```
<Rule>
  <RasterSymbolizer>
    <stop value="0" color="#000" />
    <stop value="255" color="#FFF" />
  </RasterSymbolizer>
</Rule>
```

Expected XML:

```
<Rule>
  <RasterSymbolizer>
    <RasterColorizer>
      <stop value="0" color="#000" />
      <stop value="255" color="#FFF" />
    </RasterColorizer>
  </RasterSymbolizer>
</Rule>
```

I believe this test is wrong: https://github.com/mapbox/carto/blob/master/test/rendering/raster_colorizer_comma.result

**EDIT**

Found #5, and this relevant bit:

> I think we should just live with the major caveat here that colorizing will not work (predictably/at all) unless you've explicitly set the band at the datasource level (In the case of TileMill this would mean passing band=1 to the advanced layer options)

This fixed the problem for me. Might be good to add to the docs?

**Comment by winsento** [comment]
> I think we should just live with the major caveat here that colorizing will not work (predictably/at all) unless you've explicitly set the band at the datasource level (In the case of TileMill this would mean passing band=1 to the advanced layer options)

This does not solve the problem. Carto generates the wrong XML.

**Comment by nebulon42** [comment]
@springmeyer @artemp Is omitting `<RasterColorizer>` valid Mapnik XML?

**Comment by drzhouq** [comment]
Does anyone work on this issue?

**Comment by nebulon42** [comment]
Not at the moment.

**Comment by drzhouq** [comment]
Thanks @nebulon42. How could raster color ramp even work? I am using cartodb and try to render raster in color steps, but it does not honor the steps. Cartodb forked this and also inherited the bug.

**Comment by nebulon42** [comment]
I'm afraid that currently I can't help you there, but I'm reopening this for confirmation and fixing. If you are able to go ahead with a PR, please do so.

**Comment by drzhouq** [comment]
Thanks @nebulon42. I tested it out and actually without RasterColorizer tag, mapnik renders correctly.  It is the "band" parameter in the layer section matters.  For cartodb, one has to specify "raster_band" value in layer options. Nevertheless, I will check the code so that correct tag container is created. Please close this issue if I don't send in a pull request within 10 days.

**Comment by nebulon42** [comment]
Since it is apparently working adding the container tag is not worth the hassle of finding out where it has to be added in the code. Closing again.
