### ISSUE TITLE
Multiple icons for a POI

### ISSUE THREAD

**Issue by gerbsen** [mapbox/carto#391]
Hi, not sure if this is the right place to ask (if not, where is it?) 
I'm trying to create a transit map where I have stations which have different travel types attached to them (subway, bus, rail etc.). Now my problem is, as far as I can see, I have to create a png file for each of those combination in multiple pixel sizes which sounds like a big horror to me.
Is there any way to associate more than one icon (a list of icons) to a point in cartocss?
Cheers, Daniel

**Comment by springmeyer** [comment]
Use can use SVG icons to avoid needing to procreate fixed sizes and dynamically resize with 'marker-width' parameter. Also consider using and existing resource like https://www.mapbox.com/maki/ and contributing where icons are missing.
