### ISSUE TITLE
'minzoom' is deprecated and will be removed in Mapnik 4.x, use 'minimum-scale-denominator' instead

### ISSUE THREAD

**Issue by mojodna** [mapbox/carto#394]
Same for `maxzoom` / `maximum-scale-denominator`.

Perhaps this will also clarify https://github.com/mapbox/carto/issues/385?

Refs https://github.com/mapnik/mapnik/issues/1447

**Comment by whitelynx** [comment]
I'd also like to see this done; right now, Mapnik is generating a lot of noise in our logs complaining about `minzoom` being deprecated, so I'm looking at doing a regex search/replace to manually fix it. It'd be much nicer if carto built the stylesheet with the right name.
