### ISSUE TITLE
Support YAML MML files

### ISSUE THREAD

**Issue by pnorman** [mapbox/carto#401]
JSON has a number of problems that make it unsuitable for a multi-contributor style, including code review, merge conflicts, and difficulty editing. For this reason, projects have started to move towards defining their layers in YAML and converting it to JSON, or, in the case of [Kosmtik](https://github.com/kosmtik/kosmtik), supporting reading YAML directly.

It would be useful if the `carto` program could read YAML directly, eliminating the need to convert YAML to JSON in order to produce Mapnik XML.

cc @yohanboniface

**Comment by tmcw** [comment]
I'd accept a PR for this as long as it's backwards-compatible.

**Comment by yohanboniface** [comment]
> I'd accept a PR for this

That's somewhere on my radar, but time, priorities… ;)

> as long as it's backwards-compatible.

YAML being a superset of json, that should be doable, but the devil is in the piece of code that you look for last, no? :)

**Comment by pnorman** [comment]
> YAML being a superset of json, that should be doable, but the devil is in the piece of code that you look for last, no? :)

I was thinking we'd need to autodetect yaml vs json, but you're right, a valid json file is a valid yaml file.
