### ISSUE TITLE
text label not rendered for MultiPolygons

### ISSUE THREAD

**Issue by franckl** [mapbox/carto#404]
Consider the following style : 

#mapnik2 {
  polygon-fill: orange; 
  polygon-opacity: 0.2;
  line-color: #FFF; 
  line-width: 1; 
  line-opacity: 1;
} 

#mapnik2::labels { 
  text-name: [gt];
  text-face-name: 'Open Sans Regular';
  text-size: 14;
  text-label-position-tolerance: 10;
  text-fill: orange;
  text-halo-fill: #FFFFFF;
  text-halo-radius: 2;
  text-dy: 0; 
  text-allow-overlap: true;
  text-placement: vertex; 
  text-placement-type: dummy;
  text-spacing: 0;
  text-avoid-edges: true;
  text-min-distance:50;
}

and the attached geoJSON
https://gist.github.com/franckl/8284645938d1afda02c7

It renders improperly on tileMill and also on cartoDB platform, only the one polygon has labels :
![image](https://cloud.githubusercontent.com/assets/3875803/10055669/7bfe72ec-6205-11e5-9d64-08aa11b8d352.png)

Does the issue come from Mapnik or from Carto ?

**Comment by springmeyer** [comment]
This is how mapnik works - more info at https://github.com/mapnik/mapnik/issues/3080#issuecomment-142963969
