### ISSUE TITLE
Makefile purpose

### ISSUE THREAD

**Issue by pnorman** [mapbox/carto#412]
The [Makefile](https://github.com/mapbox/carto/blob/master/Makefile) is three years old, and doesn't seem to be used when following [DEVELOPING.md](https://github.com/mapbox/carto/blob/master/DEVELOPING.md).

Is it serving a purpose?

**Comment by tmcw** [comment]
Yep, I'm pretty sure it's abandoned.

**Comment by tmcw** [comment]
Fixed by #416
