### ISSUE TITLE
Merging CartoDB changes back upstream

### ISSUE THREAD

**Issue by pnorman** [mapbox/carto#413]
I'm working at getting our carto changes merged back here to minimize different versions, and I'm wondering about what strategy to use to make it easy for you to merge.

In principle, the changes are
1. [x] 1. You can `browserify` carto and run it in the browser
2. [x] 2. carto will output to a JSON equivalent of Mapnik XML
3. [x] 3. A different mapnik-reference can be used. This is needed for passing to torque, which supports some [additional properties](http://docs.cartodb.com/cartodb-platform/cartocss/properties-for-torque/) and doesn't support some mapnik-specific ones
4. [ ] 4. Supports [`frame-offset`](http://docs.cartodb.com/cartodb-platform/cartocss/properties-for-torque/#frame-offset-number) in selectors

The cartodb tree is https://github.com/CartoDB/carto/tree/master, but Github won't diff it since it was forked before mapbox/carto was made not a fork of less/less.css. This shell might help see changes while ignoring docs and compiled files: `git diff mapbox/master cartodb/master -- `git diff mapbox/master cartodb/master --name-only | grep -v '^dist/' | grep -v '.*\.md$'``

My inclination is to first PR small non-browserify dependent changes, add browser support and tests, then add json output.

I'm not sure how to best handle 3 and 4. 3 is fairly easily to locally patch if we need to, but 4 is an addition that Mapnik wouldn't support.

**Comment by tmcw** [comment]
We're happy to bring these changes back into the mainline - so far I'm a little [confused by the direction of the browserification](https://github.com/mapbox/carto/pull/414) and note that we previously [had another attempt at bringing changes back](https://github.com/mapbox/carto/pull/379) that made things browserify compatible, but not idiomatic or consistent with CommonJS - basic tenets like avoiding globals, using require(), and using a single entry point. If carto goes commonjs with browserify support, it should go all the way and follow the right patterns.

**Comment by pnorman** [comment]
I saw the ping, but haven't managed to find you online when I've looked

**Comment by nebulon42** [comment]
As of https://github.com/mapbox/carto/commit/65fef9339536637a59d71a5985863e06880d1102 I consider 1. done.

**Comment by pnorman** [comment]
My work at CartoDB finished, so I'm not in a position to comment.

cc @rochoa

**Comment by nebulon42** [comment]
@rochoa Just to notify you that with f37bd50ee1c62f2456ffccd350d1943a4a876e7c we are now able to output a JSON variant of Mapnik XML. It still might need some polishing but basically works.

**Comment by nebulon42** [comment]
You can now specify your own reference and pass it to the renderer via the JS API. There is now also quite some documentation about that feature. With that I think carto is now flexible enough to support various use cases. Without interest from the CartoDB side I don't see No. 4 happening as I don't see the need for use cases outside of CartoDB.

I'd be happy if these additions are tested. As carto got a lot of bugfixing lately I think this would benefit CartoDB also. But I don't know how much the two forks have already diverged.

Closing for now.
