### ISSUE TITLE
disentagle docs, syntax and core carto lib

### ISSUE THREAD

**Issue by nebulon42** [mapbox/carto#434]
Currently documentation, syntax definitions and the carto parser all live in one repository. Thus, in issues and PRs all three get mixed up. I guess it would make things easier if the docs, syntax and carto would all be split up into different repositories. For that it would make sense to create a carto Github organization.

This organization could also integrate e.g. https://github.com/yohanboniface/carto-atom and similar if the owners would be willing to transfer it.

I also think that the integration with mapnik-reference is too deep. carto and mapnik-reference should be decoupled. It would make sense if carto would define its properties seperately (according to release versions of the library) and these properties would then be mapped to Mapnik XML. This would also open up the (theoretical) base for outputting something different than Mapnik XML. This decoupling would also make another repository necessary.

In this regard it would also be necessary to understand which dependencies to other Mapbox projects (e.g. Tilemill/Studio) or websites still exist in terms of documentation or syntax definition.

@tmcw @springmeyer @gravitystorm What do you think?

**Comment by tmcw** [comment]
> syntax definitions

Do you mean  text editor syntax highlighting, or something else?

**Comment by nebulon42** [comment]
> Do you mean text editor syntax highlighting, or something else?

Essentially everything that is in the `build` directory. There is https://github.com/mapbox/carto/pull/361 which targets that apparently.

**Comment by nebulon42** [comment]
Unlikely to happen, closing.
