### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by springmeyer** [mapbox/carto#449]
```
1) JS linting eslint should have no errors in lib:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

@nebulon42 looks like you added this test: https://github.com/mapbox/carto/commit/1421611d619e093af463bdc09a88683aa5249ca9. Can you think through a solution such that travis runs stay green? I presume the problem is that linking takes too long on the slow travis machines.

Possible solutions I see:
- 1) Flip to `sudo:false` at https://github.com/mapbox/carto/blob/master/.travis.yml#L3 to access more powerful travis machines. Using `sudo:false` broke things mysteriously before, but it likely doable with a little effort to figure out what broke
- 2) Increase the timeout length
- 3) Move linting out of the tape tests and move to a `pretest` target.
#3 would be my preference, but no strong opinion.

**Comment by nebulon42** [comment]
Right, I'll have a look.
