### ISSUE TITLE
renaming husl to hsluv or dropping husl support

### ISSUE THREAD

**Issue by nebulon42** [mapbox/carto#456]
Husl has changed its name to HSLuv, which is a major annoyance given that Husl colours are currently specified with husl(). I'm thinking of dropping husl support altogether as I'm missing the necessary stability of the project. Anyway, renaming or dropping husl will require moving to carto 1.0.0.

Ref https://github.com/hsluv/hsluv/issues/33

**Comment by boronine** [comment]
HSLuv creator here, sorry for the annoyance! It seems that you have these options:

1. deprecate `husl()`, drop support at 1.0
2. deprecate `husl()`, add `hsluv()`, drop `husl()` at 1.0
3. keep things as-is, wait until 1.0

On my part, I'm going to add prominent messaging to http://www.hsluv.org/ to inform people of the name change.

**Comment by nebulon42** [comment]
I think I'll go for 2.
