### ISSUE TITLE
NPM publish 0.17.1

### ISSUE THREAD

**Issue by nebulon42** [mapbox/carto#465]
0.17.1 wants to get out but after the namespace change (#457)  I don't seem to have the necessary rights/something else happens.

````
npm ERR! 404 Not found : @mapbox/carto
npm ERR! 404 
npm ERR! 404  '@mapbox/carto' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
````

@tmcw @springmeyer Could you please `npm publish` and/or check I have the needed access rights?
Thanks!

**Comment by nebulon42** [comment]
ping @tmcw @springmeyer

**Comment by nebulon42** [comment]
No longer necessary.

**Comment by gravitystorm** [comment]
@tmcw @springmeyer I'm really disappointed by this situation. After having added myself and @nebulon42 as maintainers, I thought this project was being maintained by a wider community than just Mapbox.

But in #457 you changed the package namespace without any discussion, and effectively locked @nebulon42 out from the great work he has done throughout 2017. Unilateral action like that, followed up by repeatedly ignoring his request to sort things out, is disrespectful. 

It's a great shame that @nebulon42 feels there is no choice but to fork the project entirely, but I understand his frustration. Of course, there's still an opportunity for the Mapbox team to step up and sort this situation out, and to treat us like equals in the future.

**Comment by tmcw** [comment]
I've added @nebulon42 to the carto package and un-deprecated the non-namespaced package, and happy to add you to the package.

Please, and I ask you honestly here: when I don't respond for a few days, give me the benefit of the doubt, that as a busy person, I am not cruelly, unilaterally ignoring people or treating them as less-than-equal, or any other character judgment you want to levy at me, but maybe: I'm just swamped in notifications.

I did all of the work to add more contributors to carto, to move tilemill to an independent open source project, and to add new contributors to both. I had, at all points, the option to delete the repos, or close them, or leave the status quo. But sure, I missed a notification, so I'm pretty darn evil, right?

**Comment by gravitystorm** [comment]
I can sympathise with the notification swamping, I have unsubscribed from different repositories, even those I am a maintainer of. If you don't have the bandwidth to keep up with activity in this repository that's not a problem - but if so, please consider more carefully the impact of merging PRs without discussing them with the other maintainers.

I didn't call you cruel, or evil, and increasing the invective isn't helpful. And nothing I've said is a character judgement, I have just described the various (in)actions on this topic.

If you think I was out of order for saying your behaviour was "disrespectful" I'm happy to apologise, and change my comments to "inconsiderate".

**Comment by tmcw** [comment]
Indeed.

`carto` is undeprecated and the previous owners are restored. Closing here, notify me if any other owners are required. Feel free to move forward with this project or alacarto.

**Comment by nebulon42** [comment]
@gravitystorm Thank you for your support! Let's not overemphasise this issue.

@tmcw Thanks for responding. I didn't suspect any deliberation on your side as I know that you must get a lot of notifications. However, if "you have nothing else to do" or more precisely want to get a release out in which you put in quite some hours then two weeks can be long. Just to justify my action.

If I had known that you unintentionally namespaced the package I would have taken action myself, but I assumed a decision by you and wanted to respect that.

As I said before I don't want to fragment the ecosystem, but I've come to like the separate repository for documentation and maybe other things you can do with an organization. So I'd like to suggest that we move carto to a organization in the same way as Tilemill. To ensure that the day to day governance needs as little action from your side as necessary it would be good if others could also be granted access to other parts like Appveyor or Coveralls and enough rights on the organization.

If that would be a possible way forward for you I'm happy to continue maintaining this repository. As I was very thorough I have removed myself as collaborator so you would have to add me again for that.
