### ISSUE TITLE
Move documentation to ReadTheDocs

### ISSUE THREAD

**Issue by nebulon42** [mapbox/carto#473]

**Comment by nebulon42** [comment]
Documentation is now available at https://cartocss.readthedocs.io/.

@springmeyer I don't have the rights to change the URL in the header of the repo to the new location. Could you do that for me please?
I also don't have the rights to setup a webhook that would allow the documentation to be build automatically when updating the repo. Could you help me with that or give me necessary rights?

If anybody from Mapbox requires access rights to the ReadTheDocs project just give me the user name and I'm happy to grant access.

cc @gravitystorm

**Comment by springmeyer** [comment]
> Documentation is now available at https://cartocss.readthedocs.io/.

Looks great, nice work @nebulon42 

> @springmeyer I don't have the rights to change the URL in the header of the repo to the new location. Could you do that for me please?
I also don't have the rights to setup a webhook that would allow the documentation to be build automatically when updating the repo. Could you help me with that or give me necessary rights?

I've given you access - can you try again now?

>If anybody from Mapbox requires access rights to the ReadTheDocs project just give me the user name and I'm happy to grant access.

👍  I'm `springmeyer` as well at readthedocs.

**Comment by nebulon42** [comment]
Thanks Dane, it works. I have added you to the project, let me know if something does not work as expected there.

**Comment by nebulon42** [comment]
Webhook is setup and working. So I'm closing this as fixed now.
