### ISSUE TITLE
Support for Mapnik 3.0.22

### ISSUE THREAD

**Issue by sommerluk** [mapbox/carto#498]
Hi @nebulon42 

[Mapnik 3.0.22](https://github.com/mapnik/mapnik/releases/tag/v3.0.22) has been released. Also mapnik-reference has been [updated](https://github.com/mapnik/mapnik-reference/pull/153) to 3.0.22. Furthermore a [corresponding new npm package](https://www.npmjs.com/package/mapnik-reference/v/8.10.0) has been published with version number 8.10.0. You [pointed out](https://github.com/mapnik/mapnik/pull/4004#issuecomment-434016216) that his version number change requires a new CartoCSS release, but that this would not be much work. It would be great to have a new CartoCSS release, also for playing around with [solutions for rendering of unpaved roads](https://github.com/gravitystorm/openstreetmap-carto/pull/3399) in openstreetmap-carto.

Also closes #496 ?

**Comment by nebulon42** [comment]
Done.

**Comment by sommerluk** [comment]
Thanks a lot.
