### ISSUE TITLE
Blue sky: data constants, calculations for filters

### ISSUE THREAD

**Issue by yhahn** [mapbox/carto#9]
This is a total blue sky request -- curious to see whether it's feasible/elegant to do or a total dead end. Currently our web projects use complex code to generate styles specific to the datasource, e.g. a choropleth map might need styles rendered like:

```
#layer[FIELD <= 10000] { ... }
#layer[FIELD > 10001] { ... }
```

Where 10000 is some value specific to the datasource.

I'm wondering if carto could represent certain values as pseudo-constants/calculations, e.g. `MAX(FIELD)`, `MIN(FIELD)` and furthermore evaluate calculations in filters like this:

```
/* Choropleth of 5 colors */
#layer[FIELD >= MIN(FIELD)][FIELD < MAX(FIELD) * .2] { ... }
#layer[FIELD >= MAX(FIELD) * .2][FIELD < MAX(FIELD) * .4] { ... }
#layer[FIELD >= MAX(FIELD) * .4][FIELD < MAX(FIELD) * .6] { ... }
#layer[FIELD >= MAX(FIELD) * .6][FIELD < MAX(FIELD) * .8] { ... }
#layer[FIELD >= MAX(FIELD) * .8][FIELD < MAX(FIELD)] { ... }
```

So that the styles can be reused/applied easily to any datasource. The idea here is to make visualizations much simpler to express and not require hardcoded values/external calculations. 

Just close if this is totally crazy.

**Comment by nebulon42** [comment]
I think this is unlikely to happen, but will re-open if it is supported on the Mapnik side.
